mbadrani/geppetto

test/not_mocha/PR/9358.js
| Description?  | Check that there's no error when using the global search bar of admin
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9358
| How to test?  | run node 9358.js --URL BO_URL
=> Check search page

package.json, test/not_mocha/PR/9327.js
| Description?  | Check that the product form is not broken when stock management feature is disabled
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9327
| How to test?  | run node 9327.js --URL BO_URL
=> Check product page after disabling stock management

.gitignore, README.md, package.json, test/globals.js, test/not_mocha/PR/9345.js, test/not_mocha/installPrestashop.js
| Description?  | This PR allows to check the install of shop in debug mode when composer.json file is missing and the open_basedir directive is set.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9345
| How to test?  | Run the script node test/not_mocha/PR/9345.js --URL 'http://BackOfficeURL' --LANG Language --COUNTRY Country --DB_SERVER 'DataBaseServer' --DB_USER 'DataBaseUser' --DB_PASSWD 'DataBasePassword' --RC_TARGET 'RcTargetPath'
=> Install shop

package-lock.json, package.json, test/globals.js, test/not_mocha/PR/9390.js, test/not_mocha/installPrestashop.js
| Description?  | This PR allows to check combination while trying to change size.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9390
| How to test?  | Run the script node test/not_mocha/PR/9390.js --URL 'http://FrontOfficeURL'
=> Check combination while trying to change size

package-lock.json, package.json, test/not_mocha/PR/9335.js
| Description?  | This PR allows to check the url when changing product attributes in FO.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9335
| How to test?  | Run the script node test/not_mocha/PR/9335.js --URL 'http://FrontOfficeURL'
=> Check url when changing product attributes in FO

test/not_mocha/PR/8533.js
| Description?  | This PR allows to check the duplication of products which has combinations and specific prices.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/8533
| How to test?  | Run the script node test/not_mocha/PR/8533.js --URL 'http://FrontOfficeURL'
=> Check duplication of products which has combinations and specific prices

test/globals.js, test/not_mocha/PR/9327.js, test/not_mocha/PR/9358.js, test/not_mocha/PR/9371.js
| Description?  | Check that the right products are displayed when filtering by categories in the FO
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9371
| How to test?  | run:  node test/not_mocha/PR/9371.js --URL URLFO
=> Check products when filtering by categories in the FO

test/not_mocha/PR/9388.js
| Description   |This PR allows to check the edit specific price button on Product page.
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9388
| How to test?  | Run the script node test/not_mocha/PR/9388.js --URL 'http://FrontOfficeURL'
=> Check the edit specific price button on Product page

package.json, test/helpers.js, test/mocha/campaigns/PR/9433.js, test/mocha/campaigns/common_scenarios/authentication.js, test/mocha/campaigns/common_scenarios/catalog/product.js, test/mocha/clients/common_client.js, test/mocha/selectors/BO/catalog/productsPage.js, test/mocha/selectors/BO/commonBO.js, test/mocha/selectors/BO/menu.js, test/mocha/selectors/FO/authentication.js, test/mocha/selectors/FO/homePage.js, test/mocha/selectors/FO/productPage.js
| Description   |This PR allows to add customizations field in product whitelist.
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9433
| How to test?  | Run the script TEST_PATH=PR/9433.js npm run specific-test -- --URL 'http://FrontOfficeURL'
=> Add customizations field in product whitelist

test/not_mocha/PR/8237.js
| Description?  | This PR allows to check modules restrictions to group in multishop.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/8237
| How to test?  | Run the script: node test/not_mocha/PR/8237.js --URL 'http://FrontOfficeURL'
=> Check modules restrictions to group in multishop

test/not_mocha/PR/8533.js, test/not_mocha/PR/9403.js
| Description?  | This PR allows to check the quick view button in the FO.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9403
| How to test?  | Run the script: node test/not_mocha/PR/9403.js --URL 'http://FrontOfficeURL'
=> Check the quick view button in the FO

test/not_mocha/PR/9368.js
| Description?  | This PR allows to check the url of ajax called when the product quantity changed in the FO.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9368
| How to test?  | Run the script: node test/not_mocha/PR/9368.js --URL 'http://FrontOfficeURL'
=> Check the url of ajax called when the product quantity changed in the FO

test/not_mocha/PR/8710.js
| Description?  | Check product page after creating more than 62 combinations
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/8710
| How to test?  | run:  node test/not_mocha/PR/8710.js --URL URLFO
=> Check product page after creating more than 62 combinations

package-lock.json, package.json, test/mocha/campaigns/PR/9445.js, test/mocha/campaigns/take_screenshot.js, test/mocha/clients/common_client.js, test/mocha/selectors/BO/Catalog/Products/addProduct.js, test/mocha/selectors/BO/Catalog/Products/catalog.js, test/mocha/selectors/FO/ProductPage.js, test/mocha/selectors/FO/SearchPage.js
| Description?  | Check availability product
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9445
| How to test?  | run: TEST_PATH=PR/9445.js npm run specific-test -- --URL=URLFO
=> Check product availability

test/not_mocha/PR/8533.js, test/not_mocha/PR/9285.js, test/not_mocha/PR/9327.js, test/not_mocha/PR/9335.js, test/not_mocha/PR/9358.js, test/not_mocha/PR/9371.js, test/not_mocha/PR/9388.js, test/not_mocha/PR/9390.js
| Description?  | This PR allows to check the number of products per page in FO.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9285
| How to test?  | Run the script: node test/not_mocha/PR/9285.js --URL 'http://FrontOfficeURL'
=> Check the number of products per page in FO

test/globals.js, test/not_mocha/PR/9373.js
| Description?  | This PR allows to check the payment button in checkout page with double click.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9373
| How to test?  | Run the script: node test/not_mocha/PR/9373.js --URL 'http://FrontOfficeURL'
=> Check the payment button in checkout page with double click

test/mocha/campaigns/PR/9450.js, test/mocha/campaigns/common_scenarios/advancedParameters/multistore.js, test/mocha/campaigns/common_scenarios/shopParameters/preferences.js, test/mocha/clients/common_client.js, test/mocha/selectors/BO/advancedParameters/multistore.js, test/mocha/selectors/BO/commonBO.js, test/mocha/selectors/BO/dashboardPage.js, test/mocha/selectors/BO/shopParameters/preferences.js
| Description?  | This PR allows to check the admin url when we have multishop.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9450
| How to test?  | Run the script: TEST_PATH=PR/9450.js npm run specific-test -- --URL='http://FrontOfficeURL'
=> Check admin url when we have multishop

test/globals.js, test/mocha/campaigns/PR/10109.js, test/mocha/campaigns/common_scenarios/install.js, test/mocha/clients/common_client.js, test/mocha/selectors/install.js
| Description?  | This PR allows to check the install shop with Hindi language (hi).
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/10109
| How to test?  | Run the script: TEST_PATH=PR/10109.js npm run specific-test -- --URL='http://FrontOfficeURL' --INSTALL_FOLDER_NAME='/folderName'
Note: the default value of **INSTALL_FOLDER_NAME**: '/install-dev'
=> Install shop with Hindi language (hi)

test/mocha/campaigns/PR/9405.js, test/mocha/clients/common_client.js
| Description?  | Fix 9406 as the behavior has changed
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9405
| How to test?  | run: TEST_PATH=PR/9405.js npm run specific-test -- --URL=URLFO
=> Fix 9405 as the behavior has changed

test/mocha/campaigns/PR/9145.js, test/mocha/campaigns/PR/9405.js, test/mocha/campaigns/common_scenarios/advancedParameters/multistore.js, test/mocha/campaigns/common_scenarios/catalog/product.js, test/mocha/campaigns/common_scenarios/orders/order.js, test/mocha/clients/common_client.js, test/mocha/selectors/BO/advancedParameters/multistore.js, test/mocha/selectors/BO/catalog/products/addProduct.js, test/mocha/selectors/BO/catalog/products/catalog.js, test/mocha/selectors/BO/commonBO.js, test/mocha/selectors/BO/dashboardPage.js, test/mocha/selectors/BO/orders/orderPage.js, test/mocha/selectors/BO/shopParameters/shopParameters.js, test/mocha/selectors/FO/accountPage.js, test/mocha/selectors/FO/order/checkoutOrderPage.js, test/mocha/selectors/FO/productPage.js, test/mocha/selectors/FO/shoppingCartPage.js
| Description?  | Fix tickets BOOM-4050 & BOOM-3495
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/9145, 
| How to test?  | run: TEST_PATH=PR/9145.js npm run specific-test -- --URL=URLFO
=> BOOM-4050 & BOOM-3495

test/mocha/campaigns/PR/9453.js, test/mocha/clients/common_client.js, test/mocha/selectors/BO/advancedParameters/importPage.js, test/mocha/selectors/BO/catalog/brandsAndSuppliers/brands/brands.js, test/mocha/selectors/BO/catalog/brandsAndSuppliers/suppliers/suppliers.js, test/mocha/selectors/BO/catalog/categories/categories.js, test/mocha/selectors/BO/catalog/products/catalog.js, test/mocha/selectors/BO/customers/addresses/addresses.js, test/mocha/selectors/BO/customers/customers/customers.js, test/mocha/selectors/BO/shopParameters/search.js
| Description?  | This PR allows to check import entity to be preselected.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/9453
| How to test?  | Run the script: TEST_PATH=PR/9453.js npm run specific-test -- --URL='http://FrontOfficeURL' --ADMIN_FOLDER_NAME='/folderName'
Note: the default value of **ADMIN_FOLDER_NAME**: '/admin-dev'
=> Check import entity to be preselected

test/mocha/campaigns/PR/10279.js, test/mocha/campaigns/common_scenarios/catalog/product.js, test/mocha/clients/common_client.js, test/mocha/selectors/BO/catalog/products/addProduct.js, test/mocha/selectors/FO/homePage.js, test/mocha/selectors/FO/shoppingCartPage.js
| Description?  | This PR allows to check the minimum quantity for sale.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/10279
| How to test?  | Run the script: TEST_PATH=PR/10279.js npm run specific-test -- --URL='http://FrontOfficeURL' --ADMIN_FOLDER_NAME='/folderName'
Note: the default value of **ADMIN_FOLDER_NAME**: '/admin-dev'
=> Check the minimum quantity for sale

test/mocha/campaigns/PR/10956.js, test/mocha/selectors/BO/catalog/products/addProduct.js, test/mocha/selectors/BO/catalog/products/catalog.js
| Description?  | This PR allows checking the save of product when we added two feature with the same value in the BO.
| Fixed PR? | https://github.com/PrestaShop/PrestaShop/pull/10956
| How to test?  | Run the script: TEST_PATH=PR/10956.js npm run specific-test -- --URL='http://FrontOfficeURL' --ADMIN_FOLDER_NAME='/folderName'
Note: the default value of **ADMIN_FOLDER_NAME**: '/admin-dev'
=> Check feature product
